### ISSUE TITLE
Firefox connector hickup with pdf files

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#101]
I got reports about troubles with opening a pdf file with the browser from a site for which no dedicated translator exists, where the connector doesn’t provide “Save to Juris-M (PDF)” whereas the Zotero connector does so.

It was reported in the first place for Kluwer law like https://kluwerlawonline.com/api/Product/CitationPDFURL?file=Journals\EUCL\EUCL2020025.pdf
It can also be reproduced with this openly accessible URL (and many more): https://epub.wu.ac.at/1899/1/document.pdf

What happens: when the link is opened in the browser, for a very tiny moment the connector icon shows the pdf symbol before switching to the generic webpage with snapshot symbol. Only after refreshing the page (Alt+R on the keyboard), the connector switches to the PDF symbol and can be used correctly.

**Comment by fbennett** [comment]
Thanks, I'll follow up today. It may be simply a need to update the connector to bring it level with the Zotero version.

**Comment by fbennett** [comment]
That turned out to be the problem. An updated version of the connector works correctly in Chrome and Firefox. There are a couple of wrinkles with updating:
- In Firefox, users may need to update manually from https://juris-m.github.io/release/
- In Chrome ... Google rejected my last update, so connectors installed via Chrome Web Store will be ancient---5.0.66 (!), and so will be broken in lots of ways. The rejection may just have been due to my failure to tick some administrative boxes, but if they really are blocking me, we may need to guide users on how to install dev plugins (groan).

We'll see how the review process goes. With Covid-19 in the mix, it can apparently take weeks to complete. I would recommend that people just use Firefox, if that's a viable option.

**Comment by georgd** [comment]
Thank you very much! I could update the Firefox connector from within the addons admin pane.

I wish you all the best!

**Comment by fbennett** [comment]
Oh, that's good news. I had fixed the path of the update hook in the last
revision, bit I wasn't sure if it was now working correctly.
