### ISSUE TITLE
Juris-M Connector has been disabled for violating Chrome extension store policies

### ISSUE THREAD

**Issue by dchawisher** [Juris-M/zotero#125]
https://chrome.google.com/webstore/detail/juris-m-connector/pbhldkcipcaeniadfnhhdaealdfjgbpj

**Comment by AngelaDMerkel** [comment]
I wanted to bump this because it makes the citation process quite a bit more cumbersome. The Zotero connector doesn't work directly either. Do you know what store policy was violated, considering that Zotero still have it's connector up? I suppose this is likely to be Google's fault because it has been updating requirements for plugins

**Comment by AngelaDMerkel** [comment]
I tried to build the extension from source and it fails. I don't really have the time to investigate why, but that doesn't appear to be an effective solution either.

**Comment by dv0zn3r** [comment]
I concur. Building from source did not work for me either. Also exporting a Chrome extension from a working copy of Chrome and then transferring it to a clean Chrome installation did not work. 

The only solution I have found is to install an archived copy of JurisM connector from websites that archive Chrome extension. However, it is not safe since a provider is unknown and if one cannot read the code. 

Alternatively, one may switch to Firefox as the connector for Firefox is available and operational.

**Comment by AngelaDMerkel** [comment]
Thanks for the solutions. I know Frank Bennett is still alive because based on what I can see he's still tenured staff and his twitter still posts. I hope this means that development will continue whenever he has some free time. I still struggle with there being not good standardised citations methods for legal citation in law. I recognise that lawyers have earned their reputation as luddites, but it's beyond me how major firms and legal scholarship are still so antiquated. Juris-M was the only adequate tool. I don't focus on American law but occasionally cite it, and the _Blue Book_ is obscene. 

I've attached an [unpacked copy](https://github.com/Juris-M/zotero/files/9809658/jurism-connector.zip) of the extension, but don't trust it's security because I also haven't checked and don't care enough to.

**Comment by fbennett** [comment]
Happy to report that the Chrome connector is back! Thanks to all for your patience during my absence.

**Comment by fbennett** [comment]
Closing.
