### ISSUE TITLE
Help button on Languages preference pane goes to non-existent page

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#18]
It goes to https://www.zotero.org/support/preferences/lang. If there's a different page that explains the language pane, I can get you a pull request that takes it there.

**Comment by fbennett** [comment]
Thanks for catching this -- that's not a very helpful page, is it ... hmm. Not where would be best. There is a video at the bottom of the Juris-M FAQ page (https://our.law.nagoya-u.ac.jp/howto). Maybe not the best target, but although tedious it does convey the necessaries.

There is a section of this in the MLZ book, but the book itself is thoroughly outdated, so that won't do.

A librarian at University of Colorado (Adam Lisbon) is building a page for multilingual support in Juris-M [http://libguides.colorado.edu/MLRMS](http://libguides.colorado.edu/MLRMS)

It's still in the drafting stages, but that's likely the best target, even if it's currently pretty basic.

**Comment by retorquere** [comment]
It's in pull request #19; changing the URL is trivial should it be needed.

**Comment by retorquere** [comment]
I was trying to figure out what that preference pane does. I suddenly don't feel so bad anymore about BBTs baroque preferences pane 😏 .

**Comment by retorquere** [comment]
(closed after merge of #19)
