### ISSUE TITLE
"multi" in CSL-JSON?

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#25]
In some of my tests, Juris-M generates `"multi": { "_key": {} }` for creators when (and only when) the creatorType is `reviewedAuthor`. I don't actually mind, and it's easy enough to adapt my tests to it, but it's the first time I've seen it.

**Comment by retorquere** [comment]
This is in the result from `Zotero.Utilities.itemToCSLJSON` when called in a translator BTW.

**Comment by retorquere** [comment]
For `reviewedAuthor`, Zotero and Juris-M also differ in what they output for the author name when fieldMode is 1. 

Given input 

```
{ "creatorType": "reviewedAuthor", "fieldMode": 1, "lastName": "Hermano Vianna" }
```

Zotero itemToCSLJSON  outputs 

```
"reviewed-author": [ { "literal": "Hermano Vianna" } ]
```

Where Juris-M itemToCSLJSON outputs

```
"reviewed-author": [ { "family": "Hermano Vianna", "given": "", "isInstitution": 1, "multi": { "_key": {} } } ]
```

Again, not an issue, but I didn't see this difference before.

**Comment by retorquere** [comment]
(I'm testing on m98beta2 BTW)

**Comment by fbennett** [comment]
Thanks for flagging this. It may be that a filter function meant to screen out non-standard elements may be misstepping.

**Comment by fbennett** [comment]
Actually, looking more closely, that's expected behavior. The "multi" segments carry multilingual variants. Each creator attracts a "multi" creator of its own. There is also a "multi" segment on the item, with keys for fieldnames that have multilingual variants, and sub-keys (by IETF BCP 47) for the language/script variants covered.
