### ISSUE TITLE
addons.xpi warnings persist on macOS

### ISSUE THREAD

**Issue by duncdrum** [Juris-M/zotero#37]
The nightly linked to in the readme still doesn't seem to solve the problem on macOs 10.13.3. Namely, that test fail to run locally because of errors that Travis considers `unhandled exceptions` all related to `addons.xpi` (quickly becoming my new favourite word, together with `internet explorer`).

travis log here: [travis](https://travis-ci.org/duncdrum/zotero/jobs/341404090)
local log here [local](https://my.pcloud.com/publink/show?code=XZLQhR7ZT3UkomEFxnYYMEIgmk4Lm49tl1TV)

**Comment by fbennett** [comment]
I hadn't yet attempted local tests on the Mac I use for builds, so I installed Nightly from the link Dan provided, adjusted the Mac path in `runtests.sh` to point to it, and gave it a whirl. Tests are cranking away now, and everything seems to be passing.

**Comment by fbennett** [comment]
It started throwing a bunch of timeout failures, so I've extended the timeout to see now it goes. It's an old machine, the Zotero dev environment probably loads translators a bit faster.

**Comment by fbennett** [comment]
If the bundles under `./test/tests` are run individually, they pass. It seems to be having problems running the full suite in one go with `runtests.sh`. I've changed a timeout value at line 168 of `./test/contents/runtests.js` from `10000` to `30000`, and it seems to be happier.

**Comment by retorquere** [comment]
Circle has Mac OS environment

**Comment by duncdrum** [comment]
so does travis

**Comment by fbennett** [comment]
In Travis CI, I've changed the settings in the `Juris-M/zotero` fork to run tests only when requested. Builds under Travis seem now to fail pretty reliably :-1: but the Travis build nonetheless kicks a bundled object over to AWS S3 that's used in the Zotero release chain, which I've shamelessly adopted. So at the moment I'm doing some checks with local tests, then triggering a Travis build, ignoring the eventual failure, and proceeding with the other steps needed to build the Standalone client.

The object is just a zip of the Juris-M module (sans XUL wrappers and other plugins etc) at a particular commit. Since only local tests have meaning anymore, I'm thinking that it might make sense at some point to just cut continuous integration out of the loop entirely, and save some burden on the cloud.

**Comment by fbennett** [comment]
@duncdrum Have you been able to get tests to pass locally on Mac with the recent shift to a patched FF52 as the base?

**Comment by duncdrum** [comment]
@fbennett no I haven't had time to dig into this, and get the tests to actually execute. The Zotero devs seem quite relaxed about failing tests, or lack of platform specific testing. So any work is likely to be nilled by the next upstream commit anyways.

 I m very sceptical about removing CI. IMV jurism and zotero should consider adding platform specific tests for Win (appveyor) and macOS (Travis), instead of running different FF nightlies on linux to emulate win and macOS builds.

**Comment by fbennett** [comment]
I've just put my hand-me-down Mac through the `runtests.sh` paces, and I see the errors and sticking points you have described. I see that FF creates a fresh profile when run, if we can sneak in a setting for prefs.js there to allow unsigned plugins, we might be able to squeak it through. If I come up with anything, I'll let you know.

**Comment by retorquere** [comment]
I don't know how those tests do it, but in my tests I lay out a full profile on disk including `prefs.js`, manipulate the `profiles.ini` to make sure there's a profile that points to that layout, and then start Zotero/Juris-M with `-P <profilename>`. That way you can stick whatever you want in the prefs.

edit: ini file manipulation [here](https://github.com/retorquere/zotero-better-bibtex/blob/master/features/support/env.rb#L347)

**Comment by fbennett** [comment]
I wrote that before looking at the content of `runtests.sh`, oops. That's already what they're doing there. Looks like there are two layers to running tests native on a Mac system. First is that (as on other systems) you have to hit the right version of the browser. Among the ones capable of running current Zotero/Juris-M, only FF 52esr permits the override needed to run unsigned addons (or one of the many many Nightlies, but that's a forest of uncertainty).

Once FF 52esr is in place and called from `runtests.sh`, you discover (it seems) that a few fixtures in a few of the test bundles either won't pass in the Mac environment, or almost never pass. I would have to agree with Duncan that full cross-platform testing will have to be an issue for upstream to deal with.

**Comment by duncdrum** [comment]
@fbennett so how to go about this? Setting cross-plattform testing up for jurism is relatively easy, given that we already have a Travis suite. 
I'd be happy to create a PR to that effect, or should we increase the heat over at zotero?

P.S.: agreed, about those nightlies a current FF ESR should at least get us to august.

**Comment by fbennett** [comment]
@duncdrum I don't see a path to a working solution at this end, really. The tests can be made to pass (pretty) reliably locally under Linux, if bundles are run separately, and if translator loading is turned off for certain bundles; but the rate of failure in Travis CI makes it pretty much useless currently. I don't feel too put out about it, since the status quo is still _much_ better than the situation at the start of MLZ development (i.e. base-jumping each release, with no automated tests at all).

**Comment by fbennett** [comment]
I've been able to get clean test runs locally on Mac OSX. I had been running the tests with Terminal maximized. Something (thread priority?) changes when the little browser instance showing in the upper left-hand corner of the terminal is obscured by another maximized window. With Terminal reduced to an ordinary window, everything [works fine](https://groups.google.com/forum/#!topic/zotero-dev/5ghBEow7r6k).

Rather than wading through the Nightly forest looking for a suitable download, I just used the `-x` option to `./runtests.sh` to point at the production `firefox` binary at `./zotero-standalone-build/xulrunner/Firefox.app/Contents/MacOS/firefox`. All tests pass.

Travis CI still fails miserably, but that may be due to the same (thread priority?) issue that causes failures with maximized Terminal window. Firefox has a headless mode now, but it appeared in FF56, so we can't use it for Standalone.

Not completely satisfying, but it's good to have the assurance of local test runs.
