### ISSUE TITLE
FYI: performance in new release?

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#66]
Just as an FYI: the performance of my tests between Zotero and Juris-M seems to be diverging. Juris-M used to start slower but would otherwise be sort of same speed, but the difference seems more significant now: https://travis-ci.org/retorquere/zotero-better-bibtex/builds/592764837 . The same tests run on both. Maybe it's a fluke, I'll keep an eye out.

**Comment by retorquere** [comment]
Seems pretty structural so far. Mind that my tests focus on import/export.

**Comment by fbennett** [comment]
Jurism will start up more slowly than Zotero, partly because of the language and jurisdiction data that it loads, and partly because of additional code controlling the display of the item tree. For the automated tests, there is a toggle somewhere in there that can be used to load only a minimal set of language tags, if that will help.

**Comment by retorquere** [comment]
Naah, it's fine. I prefer to use as close to production use as testing allows. I've started using a profile where zotero has already started once and that makes enough of a difference.
