### ISSUE TITLE
Auto Convert Citations to Volume References for Appeals

### ISSUE THREAD

**Issue by ClintCrab** [Juris-M/zotero#67]
WHAT: Need to re-format and modify citations based on a Record on Appeal (ROA). In an intial brief for Appeals, the citations are to the respective court documents. But once those documents, evidence, orders are consolidated into volumes called the ROA Volume X, (each volume is limited to 500 pages) then the new citation could be automated if a list of its starting page within the ROA is given.

EXAMPLE AUTO CONVERT to a Bound Volume of Citations
FROM: Judge McFaddin, Temp Order Ruling, 30 Nov 2015 page 7
TO: ROA Volume 2 page 56.
GIVEN: that the subject document starts at page 50 in the Record on Appeal

WHO: I am a full stack developer and I'm curious if I could do the contribution for the feature if necessary. I code for mysql, php, javascript primarily using dreamweaver. I am a PRO SE defendant appealing a divorce ruling and realizing anyone doing an appeal could use this.

HOW: It seems if I had 2, or 3 fields to enter in Zotero for my citation I could convert the citations. The fields would hold the label for "ROA" the Volume, and then the starting position within the volume for that document. From that info then the entire brief could be re-numbered thus if the referenced document calls for page 7, and it's starting place in the ROA is page 50, the code will simply add the difference putting it at page 56.

------Below is the response from Zotero GitHub and pointing me to Juris-M GitHub-----

bwiernik yesterday at 2:48am
@fbennett Do you have a suggestion for holding this sort of item? Is there something in Jurism that would be a good fit?

clintcrabtree yesterday at 11:20pm
In Juris-M there are fields that I've never seen get populated i.e. via google schoolar or google case, but I've only managed a couple appeals with about 55 references. Fields that could be temporarily used and seem common to the various reference modes such as (book, book section, document, journal article, Newspaper article, manuscript, etc) are the fields labeled (`call number`, `rights`, and `extra`). These could be used for such purposes. Such as using the `call number` field and entering text such as ROA Volume I, and then in the `extra` field entering the starting position page number. There would need to be a tool in the document processing side to convert from `individual refernce mode` to `bound volume reference mode`

bwiernik today at 1:14am
I wouldn’t suggest trying to hack something together. I imagine Jurism can already accommodate such items, but my knowledge of legal citation isn’t enough to offer specific advice. You could try the mailing lists listed at juris-m.github.io

**Comment by fbennett** [comment]
@ClintCrab: Sorry for taking such a very long time to respond to your post. I've just completed a full implementation of the Indigo Book (a restatement of the Bluebook rules), for which I needed to do a considerable amount of field-dependent conditional rendering to cover the rag-tag variety of citation forms that it treats as "uniform." If you visit the project website, you can navigate to [a copy of the Indigo Book that has a link for submission of novel citation forms](https://juris-m.github.io/indigobook+jurism). If you file the desired output there, together with a description of the use case, indicating the jurisdiction where the rule applies, the Indigo Book editors can take it up for consideration.

(One caveat is that we wouldn't want to do maths on field content, since in Zotero/Jurism "number" fields are just a subcategory of string variables, and can carry arbitrary content.)
