### ISSUE TITLE
What is the expected return value for `parseDateToObject('2004 [1929]')`?

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#7]
It returns `{ year: '1929' }`, but I had expected to see (and indication of) a literal date being present.

**Comment by fbennett** [comment]
It was built to run in the UI against dirty dates, so it is not fussy about syntax; it does its best to find date elements in the input, and it if finds something that fits, that's what you get in the parse.

Zotero itself parses dates into a uniform internal syntax, and stores the literal string alongside it. The storage format doesn't support ranges. Rather than implementing a standard storage format that does support ranges (and probably breaking sync and a bunch of other stuff in the process), I opted for this very-forgiving parser, which works on the user-edited input string.

If you need something with more strict constraints, another tool would probably be appropriate.

**Comment by retorquere** [comment]
Hmm. Bummer.
