### ISSUE TITLE
Juris-M ignores inheritable `name-delimiter`

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#86]
citeproc-js ignored inheritable `name-delimiter`, so instead of the specified `"/"`, the default `", "`

This was fixed in `citeproc-js` with https://github.com/Juris-M/citeproc-js/commit/65d0efa95c9c22f3bd20817a211f08d7a6ad06f9 – nevertheless, when citing with Juris-M it resurfaces with `legal_commentary`. At least, `book` and `article-journal` behave correctly.

The screenshot from the bibliography shows the items from the tests `chapCommentary_test014.txt` (Schwimann/Kodek) and `chapCommentary_test016.txt` (Korinek/Holoubek) as well as `book_test008.txt` (Alker/Hölter) for comparison, cited using the style `jm-leg-cit-rechtsquellenverzeichnis-literaturverzeichnis.csl`. 

![image](https://user-images.githubusercontent.com/214002/94898897-9e26a080-0492-11eb-80d1-a163a738a5ba.png)

**Comment by fbennett** [comment]
Thanks again. Will take a look soon.

**Comment by fbennett** [comment]
Fixed in citeproc-test-runner, and the fix for Jurism is processing now, will be up in a few minutes.

Hitting this was beneficial in revealing a bug in the way Jurism and the processor handle names. The test has a single name in the "family" field. That CSL-JSON imports to Jurism as a two-field name with a value only in the "lastName" subfield. When that is shipped back to the processor, Jurism is messily composing it with a value in "family", the same value again in "literal", and an empty string in "given". When the processor sees *that*, it handles it as an institution ... and institution delimiters were defaulting to "``, ``".

The immediate fix was only to remove the default delimiter value from the ``cs:institution`` node that ``citeproc-js`` silently inserts into ``cs:names`` nodes. Then delimiter inheritance works properly, and the client renders things correctly. Whew!

**Comment by fbennett** [comment]
I overlooked a couple of things, one further update just went live. The latest test runner will validate against the ``randnummer``term, and the test runner and Jurism client now implement the ``country`` test.
