### ISSUE TITLE
Add ECLI field to legal cases

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#94]
ECLI will arrive in CSL with v 1.1, together with a new identifier variable (https://github.com/citation-style-language/schema/issues/350). However, there’s probably still quite some time until that arrives in any implementation.

I expect a significant increase in European Juris-M users who need the ECLI in their data. The current workaround is to use DOI in data and styles. This has the double drawback that this field is not visible in the UI for cases and has to be entered manually and when CSL 1.1 arrives, the data will have to be changed manually.

Therefore, a temporary CSLm extension in the form of a new variable `ecli` (or `legal_eid`) would be very welcome. Once CSL 1.1 arrives, it can be retired and the data transferred automatically to the new `cs:identifiers@type="ecli"`.

**Comment by fbennett** [comment]
I'm not keen on adding a Europe-specific field for the identifier, but we could add DOI to the ``legal_case`` type, and adopt a convention that ECLI identifiers are prefixed with ``ecli:``. With that in place, we could make the DOI label clickable, calling EurLex in the browser on the identifier, and sorts on the DOI field would group ``ecli:`` entries, so that they are not intermixed with vanilla DOIs. Would that serve?

**Comment by fbennett** [comment]
> ... With that in place, we could make the DOI label clickable, calling EurLex in the browser on the identifier ...

Looking at Eur-Lex again, I see that I made a couple of false assumptions there: ECLI identifiers begin with "ECLI" anyway, so there's no need for any prefix; and Eur-Lex uses a completely separate CELEX number to identifier instruments in the archive, so building a clickable link isn't going to work. We can disable clicking for ECLI identifiers, though, so that Jurism doesn't confusingly attempt to treat them as resolvable DOIs.

**Comment by fbennett** [comment]
... looking a bit further, I see that Zotero already handles "disabling." The DOI label is clickable only when the field contains a valid DOI. An ECLI doesn't match the pattern, so it is disabled automatically. So this would be very simple to deploy in Jurism.

**Comment by fbennett** [comment]
... I misspoke about one other thing above. I see that DOI is not among the fields that can be added to the center-panel listing. So the idea about clustering in a sort there is not relevant.

Adding DOI to the case type is probably the best we can do for the present, so I'll add that in and push a beta release with that, and with the institution fallback mentioned in the other thread, so you can take a look.

**Comment by georgd** [comment]
Yes, adding the DOI field to case is fine and you already found out that all the other things aren‘t necessary here :). I’d have proposed it as an alternative, if you hadn’t come up with it. What I wonder: can ECLIs in the DOI field be moved automatically, once CSL 1.1 arrives?

The advantage of this solution is that it’s compatible with current workarounds in vanilla CSL styles.

**Comment by fbennett** [comment]
Excellent. ECLI values can definitely be migrated in an upgrade. Jurism inherits a schema migration mechanism from Zotero that is invoked before opening the database. In pre-5.0 development there were frequent changes of a similar kind, transforming content or moving it between fields. In this case, we would be shunting value beginning with "ECLI:" to the new field. Should be no problem.
